# Specify a base image
FROM node:16-alpine

USER node
 
RUN mkdir -p /home/node/app
WORKDIR /home/node/app

# Install some dependencies
COPY --chown=node:node package.json .
RUN npm install
COPY --chown=node:node . .

# Default command
CMD ["npm", "start"]